{% set name = "skyllh" %}
{% set version = "26.0.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/skyllh-{{ version }}.tar.gz
  sha256: 514280b7177bc93a56fdb9722fde5e7189a7490464aac94b0d430e1d12e1a5d2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=80
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - astropy-base >=7.0
    - matplotlib
    - numpy
    - pyyaml
    - scipy
    - tqdm

test:
  imports:
    - skyllh
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/icecube/skyllh
  summary: The SkyLLH framework is an open-source Python3-based package licensed under the GPLv3 license. It provides a modular framework for implementing custom likelihood functions and executing log-likelihood ratio hypothesis tests. The idea is to provide a class structure tied to the mathematical objects of the likelihood functions.
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - tomaskontrimas
